### PR TITLE
Troubleshooting Crowdin integration

### PR DESCRIPTION
**Pull request by BatoolMM**
Looking at the crowding project, the file which is translated to Japanese (CoC) doesn't exist on the GitHub repo - it seems you uploaded it directly from the local machine. I added the file to the repo and change the source path in the `crowdin.yml` to capture all the files not just `.srt`. Let me know if this fix the problem @kozo2 ?

### CODE REVIEW

**Comment by kozo2** [comment]
Thank you @BatoolMM !
I'll try your suggestion now.

**Comment by kozo2** [comment]
@BatoolMM I replaced the old `crowdin.yml` to 
```
files:
  - source: '**/*'
    translation: '''%language%_transcripts/%original_file_name%'''
```
.
But still the translated srt was not uploaded to this repository.

**Comment by BatoolMM** [comment]
This is because the translated `CoC.md` is outside the repo (blue) whereas the one which is in the repo (red) is still untranslated. The files inside this repo is showing in crowdin as `/
bioc-talks-and-transcripts/main`. You should remove the blue one and move all the translations to the red one.

Screen Shot 2021-12-09 at 7 09 48 AM

> @kozo2 Try not to upload anything manually in crowdin, add them to the repo and they will be added to crowdin automatically. let me know if this is not clear! 

A PR will open with the translation made after an hour or 10 minutes as you can specify that in GitHub integration within Crowdin in "Sync schedule"
 
Screen Shot 2021-12-09 at 7 24 46 AM

**Comment by kozo2** [comment]
Thanks @BatoolMM 
Now I don't need the `CoC.md`, and I removed it.
And I made my repo extremely simple.
https://github.com/kozo2/bioc-talks-and-transcripts
I also set the sync schedule to 10 minutes.
But still my Japanese translation in Crowdin
image
is not pushed to https://github.com/kozo2/bioc-talks-and-transcripts .
Do you have any ideas?

**Pull request closed without merging**
